/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#0c120e",
        "background": "#0c120e",
        "surface-dim": "#080d09",
        "surface-bright": "#2a3d2f",
        "surface-variant": "#223326",
        "surface-container-lowest": "#080d09",
        "surface-container-low": "#101812",
        "surface-container": "#152018",
        "surface-container-high": "#1c2b20",
        "surface-container-highest": "#243729",
        "primary": "#96d5a3",
        "primary-container": "#14532d",
        "primary-fixed": "#b1f2be",
        "primary-fixed-dim": "#96d5a3",
        "on-primary": "#96d5a3",
        "on-primary-container": "#96d5a3",
        "on-primary-fixed": "#00210d",
        "on-primary-fixed-variant": "#12512c",
        "secondary": "#ffb77d",
        "secondary-container": "#542d00",
        "secondary-fixed": "#ffdcc3",
        "secondary-fixed-dim": "#ffb77d",
        "on-secondary": "#4d2600",
        "on-secondary-container": "#ffb77d",
        "on-secondary-fixed": "#2f1500",
        "on-secondary-fixed-variant": "#6e3900",
        "tertiary": "#6bd8cb",
        "tertiary-container": "#00403a",
        "tertiary-fixed": "#89f5e7",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-tertiary": "#003732",
        "on-tertiary-container": "#6bd8cb",
        "on-tertiary-fixed": "#00201d",
        "on-tertiary-fixed-variant": "#005049",
        "error": "#ffb4ab",
        "error-container": "#5c0c11",
        "on-error": "#ffffff",
        "on-error-container": "#ffb4ab",
        "outline": "#839587",
        "outline-variant": "#223326",
        "on-surface": "#e1e7e2",
        "on-surface-variant": "#a5b3a7",
        "inverse-surface": "#dee4dd",
        "inverse-on-surface": "#2c322d",
        "inverse-primary": "#2e6a41",
        "surface-tint": "#96d5a3",
        "on-background": "#e1e7e2",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "margin-desktop": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "telemetry-sm": ["JetBrains Mono", "monospace"],
        "telemetry-md": ["JetBrains Mono", "monospace"],
        "telemetry-lg": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "700" }],
        "telemetry-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "telemetry-md": ["14px", { lineHeight: "18px", fontWeight: "500" }],
        "telemetry-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
